name: deploy

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Installing Dependencies
        run: nvmrc=$(cat .nvmrc)
        uses: setup-node@v1
        with:
          node-version: $nvmrc
        run: yarn install
        run: ember build --env=production
      - name: Create temp Directory
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_PRODUCTION }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATE_KEY }}
            script: mkdir -p ~/temp
      - name: Upload Build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist"
          target: "temp"
      - name: Replace New Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: rm -rf ~/frontends/hiringblocks/* && cp -rf ~/temp/dist/* ~/frontends/hiringblocks && rm -rf ~/temp